/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.Dao;
import Model.Appoints;
import Model.LogIn;
import java.util.List;
import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author hp
 */
public class Appointment extends javax.swing.JFrame {

    /**
     * Creates new form Appointment
     */
    public Appointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        departmentp = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        doctorp = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        dayp = new javax.swing.JComboBox<>();
        timep = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        sendbtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        welcomelbl = new javax.swing.JLabel();
        reqapplbl = new javax.swing.JLabel();
        sentlbl = new javax.swing.JLabel();
        logoutlbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        patientlbl = new javax.swing.JLabel();
        presclbl = new javax.swing.JLabel();
        namep = new javax.swing.JTextField();
        emailp = new javax.swing.JTextField();
        phonep = new javax.swing.JTextField();
        insurancep = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 179, 173));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REQUEST AN APPOINTMENT");

        jLabel2.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");

        jLabel8.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Names:");

        jLabel9.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone Number:");

        jLabel3.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Department:");

        departmentp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Medicine", "Dentistry", "Cardiology", "Cancer", "Surgery", "Gynecology", "Blood Test", " " }));
        departmentp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentpActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Doctor:");

        doctorp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorpMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Day:");

        dayp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        timep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning(8am-11am)", "Noon(12pm-2pm)", "Afternoo(3pm-6pm)" }));

        jLabel12.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Time:");

        sendbtn.setBackground(new java.awt.Color(0, 0, 0));
        sendbtn.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        sendbtn.setForeground(new java.awt.Color(255, 255, 255));
        sendbtn.setText("SEND");
        sendbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Insurance");

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\APEX HEALTH HAVEN last.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel14))
        );

        welcomelbl.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        welcomelbl.setText("Welcome");
        welcomelbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        welcomelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                welcomelblMouseClicked(evt);
            }
        });

        reqapplbl.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        reqapplbl.setText("RequestAppointment");
        reqapplbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reqapplbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reqapplblMouseClicked(evt);
            }
        });

        sentlbl.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        sentlbl.setText("View Sent Appointment");
        sentlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sentlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sentlblMouseClicked(evt);
            }
        });

        logoutlbl.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        logoutlbl.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\icons8-logout-30.png")); // NOI18N
        logoutlbl.setText("Logout");
        logoutlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutlblMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\icons8-user-24.png")); // NOI18N

        patientlbl.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        patientlbl.setText("Patient");

        presclbl.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        presclbl.setText("Prescrption and comments");
        presclbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        presclbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                presclblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(presclbl)
                    .addComponent(logoutlbl)
                    .addComponent(reqapplbl)
                    .addComponent(welcomelbl)
                    .addComponent(sentlbl)
                    .addComponent(patientlbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(patientlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addComponent(welcomelbl)
                .addGap(18, 18, 18)
                .addComponent(reqapplbl)
                .addGap(18, 18, 18)
                .addComponent(sentlbl)
                .addGap(18, 18, 18)
                .addComponent(presclbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(logoutlbl)
                .addGap(26, 26, 26))
        );

        insurancep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "RSSB", "Radiant", "Other", " " }));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(departmentp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phonep)
                            .addComponent(emailp)
                            .addComponent(namep)
                            .addComponent(insurancep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doctorp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dayp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(112, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(78, 78, 78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(sendbtn)
                                .addGap(216, 216, 216))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insurancep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departmentp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(doctorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dayp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(timep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(sendbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbtnActionPerformed
        if(idtxt.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Insert your Id","Field is mandatory",JOptionPane.WARNING_MESSAGE);
       
       }else if(namep.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Insert your FullNames","Field is mandatory",JOptionPane.WARNING_MESSAGE);
       }else if(emailp.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Insert your email","Field is mandatory",JOptionPane.WARNING_MESSAGE);
       }else if(phonep.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Insert your phone number","Field is mandatory",JOptionPane.WARNING_MESSAGE);
       }
       else if(String.valueOf(insurancep.getSelectedItem()).trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Choose an insurance","Field is mandatory",JOptionPane.WARNING_MESSAGE);
       }else if(String.valueOf(departmentp.getSelectedItem()).trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Choose department","Field is mandatory",JOptionPane.WARNING_MESSAGE);
       }else if(String.valueOf(doctorp.getSelectedItem()).trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Choose Doctor","Field is mandatory",JOptionPane.WARNING_MESSAGE);
       }else if(String.valueOf(timep.getSelectedItem()).trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Pick time","Field is mandatory",JOptionPane.WARNING_MESSAGE);
       }
       //2. Validate the length of characters 
      
       else{     
        
        
        Appoints Obj = new Appoints();
            
            Obj.setName(namep.getText());
            Obj.setEmail(emailp.getText());
             Obj.setPhone(phonep.getText());
            Obj.setInsurance((String)insurancep.getSelectedItem());
            Obj.setDepartment((String)departmentp.getSelectedItem());
            Obj.setDoctor((String)doctorp.getSelectedItem());
            Obj.setDay((String)dayp.getSelectedItem());
            Obj.setTime((String)timep.getSelectedItem());
            Obj.setId(Integer.parseInt(idtxt.getText()));
           
            //call dao
            Dao dao = new Dao();
           // dao.createuser(Obj);
            String feedBack = dao.sendappointment(Obj);
             JOptionPane.showMessageDialog(this, feedBack);
       }
    }//GEN-LAST:event_sendbtnActionPerformed

    private void welcomelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_welcomelblMouseClicked
         LogIn loggedInUser = new LogIn();
        MainForm mainForm = new MainForm(loggedInUser);
        mainForm.setVisible(true);
        mainForm.pack();
        mainForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_welcomelblMouseClicked

    private void reqapplblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reqapplblMouseClicked
        Appointment apt = new Appointment();
        apt.setVisible(true);
        apt.pack();
        apt.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_reqapplblMouseClicked

    private void sentlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sentlblMouseClicked
       
        SentAppointments apt = new SentAppointments();
        apt.setVisible(true);
        apt.pack();
        apt.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_sentlblMouseClicked

    private void logoutlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutlblMouseClicked
        Login apt = new Login();
        apt.setVisible(true);
        apt.pack();
        apt.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_logoutlblMouseClicked

    private void presclblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_presclblMouseClicked
        Prescriptions apt = new Prescriptions();
        apt.setVisible(true);
        apt.pack();
        apt.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_presclblMouseClicked

    private void departmentpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentpActionPerformed
        Appoints Obj = new Appoints();
        Obj.setDepartment((String)departmentp.getSelectedItem());
        Dao dao = new Dao();
       dao.depDoctors(Obj);
       List<String> doctorsList = Obj.getDoctors();

    // Assuming doctorp is a JComboBox
    doctorp.setModel(new DefaultComboBoxModel<>(doctorsList.toArray(new String[0])));
    }//GEN-LAST:event_departmentpActionPerformed

    private void doctorpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorpMouseClicked
       JOptionPane.showMessageDialog(this, "First Choose Department to be able to see doctors");
    }//GEN-LAST:event_doctorpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> dayp;
    private javax.swing.JComboBox<String> departmentp;
    private javax.swing.JComboBox<String> doctorp;
    private javax.swing.JTextField emailp;
    private javax.swing.JTextField idtxt;
    private javax.swing.JComboBox<String> insurancep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logoutlbl;
    private javax.swing.JTextField namep;
    private javax.swing.JLabel patientlbl;
    private javax.swing.JTextField phonep;
    private javax.swing.JLabel presclbl;
    private javax.swing.JLabel reqapplbl;
    private javax.swing.JButton sendbtn;
    private javax.swing.JLabel sentlbl;
    private javax.swing.JComboBox<String> timep;
    private javax.swing.JLabel welcomelbl;
    // End of variables declaration//GEN-END:variables
}
